version: '3.8'
services:
  admin:
    build: admin/.
    ports:
      - "8080"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

  api:
    build: api/.
    ports:
      - "3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      SINGLESTORE_USER: ${SINGLESTORE_USER}
      SINGLESTORE_PASSWORD: ${SINGLESTORE_PASSWORD}
      SINGLESTORE_HOST: ${SINGLESTORE_HOST}
      SINGLESTORE_DATABASE: ${SINGLESTORE_DATABASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  singlestore:
    image: 'singlestore/cluster-in-a-box'
    ports:
      - 3306:3306
      - 8080
    environment:
      LICENSE_KEY: BGY0ODA3MDcwODIwYzRlYzViMmVkZWExYTRkNzZmOWYxAAAAAAAAAAAEAAAAAAAAACgwNQIZANJGKRUDDCYFX4haK46B55YkAsW4x/cWdAIYOVuezYO4tudv70akJF4XyorAC2lWgQwsAA==
      ROOT_PASSWORD: Tomisl@vgrad123
      START_AFTER_INIT: 'Y'
    restart: always