version: '3.8'
services:
  admin:
    build: admin/.
    ports:
      - "8080"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

  api:
    build: api/.
    ports:
      - "3000"
    environment:
      SINGLESTORE_USER: ${SINGLESTORE_USER}
      SINGLESTORE_PASSWORD: ${SINGLESTORE_PASSWORD}
      SINGLESTORE_HOST: ${SINGLESTORE_HOST}
      SINGLESTORE_DATABASE: ${SINGLESTORE_DATABASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
